### ISSUE TITLE
fallbacks.json misses entry for West Frisian - fry

### ISSUE THREAD

**Issue by mboeringa** [kartotherian/babel#18]
I don't know if this is actually the right Github to report this, but looking at the fallbacks.json file included here, I noticed that West Frisian, the second official language spoken in the Friesland province of the Netherlands, is missing:

https://en.wikipedia.org/wiki/Frisian_languages

I think a **"fry":"nl"** needs to be added. The other two Frisian languages (North and Saterland Frisian - frr and stq) are currently listed.

**Comment by mboeringa** [comment]
Reading a bit more about the map internationalization project, I realized the missing fallback may in fact be a conscious choice of some Dutch Frisian people active on the Wiki's, if they prefer to rather see a potentially incomplete map entirely in Frisian, rather than one "artificially" completed with NL names by means of fallback.

This does raise a question though: is the specific choice to in- or exclude a certain "fallback" in the fallback.json documented somewhere? This could help prevent "language fallback wars", where some people request a fallback, while others specifically do not want them...

Maybe the JSON could also use an extension, with an "active/inactive" attribute to show and manipulate whether a certain known possible fallback is active or not. At least you would then know that the fallback option wasn't simply missing because of an oversight.

E.g.

**"fry": "nl/0"** for an inactive fallback option
and 
**"ab": "ru/1"** for an active fallback

**Comment by nyurik** [comment]
Thanks @mboeringa, interesting idea. I feel the biggest problem is that babel does not know the language of the `name` tag to decide if it should be used or not.  That's why I started the [default_language project](https://wiki.openstreetmap.org/wiki/Key:default_language).  Many places in OSM have been already marked with it, but substantial work needs to be done to make it usable in Babel. There are two ways - either bring that data into each feature of the vector tiles, or compile all regions into a single geojson, and use it as a spacial lookup.

**Comment by catrope** [comment]
Note that the language code for West Frisian is `fy`, not `fry`.

The fallbacks here were copied from MediaWiki, and in MediaWiki `fy` does not have a fallback on `nl`. For that reason, and because of the default language issue, we won't add such a fallback unless the Frisian wiki community requests it (or unless MediaWiki's fallback changes).
